export default {
  'react': 'React',
  'react-dom': 'ReactDOM',
  'ethers': 'ethers',
  'depay-react-dialog-stack': 'ReactDialogStack',
  'depay-react-dialog': 'ReactDialog',
  'depay-react-shadow-dom': 'ReactShadowDOM',
  'depay-web3-blockchains': 'Web3Blockchains',
  'depay-web3-wallets': 'Web3Wallets',
  'depay-web3-payments': 'Web3Payments',
  'depay-web3-tokens': 'Web3Tokens',
  'depay-web3-client': 'Web3Client',
  'depay-web3-exchanges': 'Web3Exchanges',
  'depay-web3-constants': 'Web3Constants',
  'depay-local-currency': 'LocalCurrency',
  'depay-react-token-image': 'ReactTokenImage',
  'react-error-boundary': 'ErrorBoundary',
  'react-rangeslider': 'ReactRangeslider',
  '@depay/walletconnect': 'WalletConnect',
  'decimal.js': 'Decimal',
}
