export default {
  '@depay/local-currency': 'LocalCurrency',
  '@depay/react-dialog': 'ReactDialog',
  '@depay/react-dialog-stack': 'ReactDialogStack',
  '@depay/react-shadow-dom': 'ReactShadowDOM',
  '@depay/react-token-image': 'ReactTokenImage',
  '@depay/walletconnect': 'WalletConnect',
  '@depay/walletconnect': 'QRCodeModal',
  '@depay/web3-blockchains': 'Web3Blockchains',
  '@depay/web3-client': 'Web3Client',
  '@depay/web3-constants': 'Web3Constants',
  '@depay/web3-exchanges': 'Web3Exchanges',
  '@depay/web3-payments': 'Web3Payments',
  '@depay/web3-tokens': 'Web3Tokens',
  '@depay/web3-wallets': 'Web3Wallets',
  'ethers': 'ethers',
  'react': 'React',
  'react-dom': 'ReactDOM',
  'react-error-boundary': 'ErrorBoundary',
  'react-rangeslider': 'ReactRangeslider',
  'decimal.js': 'Decimal',
}
